### ISSUE TITLE
How would I go about adding Tailwind

### ISSUE THREAD

**Issue by netflakes** [still-ex/still#121]
Sorry if this is an annoying question - but how would I go about adding a CSS library like TAILWIND - I know how to add this to an existing Phoenix app - but if you could give a few pointers that would be awesome - Thanks for your hard work creating this project...

**Comment by gabrielpoca** [comment]
Hey @netflakes we are about to finish some work that will make it super easy to integrate node packages. There are so many ways we can do this that we need to test a bunch of things. Still (:p) I didn't want to leave you waiting so I made a little example to get you started https://github.com/still-ex/tailwind_example some of this will not be necessary afterward. There are two commits, the first is just the scaffold, the second is what you want.

I'll keep this issue open until we have that other package.

**Comment by gabrielpoca** [comment]
Hey @netflakes are you still looking for tailwind support? We are just doing some final testing on the snowpack support [here](https://github.com/still-ex/still_snowpack) and I already updated [my website with tailwind](https://github.com/gabrielpoca/gabrielpoca.com/tree/f6aad2d58d85221c62e900717fcc6398ff13c9c2). If you have the time, let me know what you think!

**Comment by gabrielpoca** [comment]
Fixed in https://github.com/still-ex/still/commit/c954a8bc6ae9b88e9e7e77f3acbc49f6aeec2980
