### ISSUE TITLE
Rename View Helpers to Template Helpers

### ISSUE THREAD

**Issue by gabrielpoca** [still-ex/still#125]
@frm I think we should rename View Helpers to Template Helpers. We are calling those files _templates_, not _views_. I think the only reason we called it views is because we were thing about Phonix. What do you say?

**Comment by frm** [comment]
On one hand I'd prefer it to be clear and someone familiar with Phoenix would know what this is about. On the other hand, I'd prefer to not use Phoenix as a staple and to have clear terms for well defined concepts.

Let's do it.

**Comment by hgg** [comment]
Can I take this one? Would love to contribute.

**Comment by frm** [comment]
@hgg go for it 👍
