### ISSUE TITLE
Look into the slow tests on the CI

### ISSUE THREAD

**Issue by gabrielpoca** [still-ex/still#127]
We need to run tests with `mix test --timeout 120000` on the CI because they are taking too long to finish. I believe this is related to our change to remove `imageflow` from still, which was much faster than ImageMagick. This is not an issue, because the tests pass, but each test shouldn't take this long.

**Comment by frm** [comment]
How are the tests locally?

**Comment by gabrielpoca** [comment]
They seem to be fine. I guess we have to cache the `_site` for tests.

**Comment by gabrielpoca** [comment]
It seems like this is no longer an issue.
