### ISSUE TITLE
mix still.compile should fail when there's an error

### ISSUE THREAD

**Issue by gabrielpoca** [still-ex/still#136]
When we are compiling a site for deployment, we need to know if it failed, otherwise will be deploying an incomplete site.

**Comment by frm** [comment]
For reference: see step `Run MIX_ENV=site mix still` of [this build](https://github.com/still-ex/still/runs/2055881161).

**Comment by gabrielpoca** [comment]
Fixed in https://github.com/still-ex/still/commit/bfd6e6bd1601c17a47129db312ef7a8971b063ac
