### ISSUE TITLE
Depending on still-ex/still_imageflow as a dev dependency

### ISSUE THREAD

**Issue by hgg** [still-ex/still#145]
Still has a dependency on an image processor for running tests, but none is included.
Since we have https://github.com/still-ex/still_imageflow, why doesn't Still depend on it on the dev & test environments only? 

I.E. adding `{:still_imageflow, "~> 0.1.0", only: [:dev, :test], runtime: false}` to the dependencies.

Otherwise, we have no way to install and run the tests in a straightforward way, unless we have ImageMagick installed for some reason.

**Comment by gabrielpoca** [comment]
Yeah, you need to have imagemagick on the system. We used to have imageflow as a dev dependency, but it requires the rust toolchain and it increases the compilation times by a lot. It doesn't feel right to have people install rust and compile imageflow to contribute still and installing imagemagick is a bit simpler.

**Comment by hgg** [comment]
Oh, alright. I'll edit #146 to say that you need to have imagemagick installed.
