### ISSUE TITLE
HTML Preprocessor

### ISSUE THREAD

**Issue by elinol** [still-ex/still#153]
I'm trying to add a preprocessor in for my .html-files since they contain front matter, but they are ignored on compilation.

```
preprocessors: %{
    ".html" => [AddContent, EEx, Frontmatter, OutputPath, AddLayout, Save]
  }
```
Are .html files maybe excluded per se?

**Comment by gabrielpoca** [comment]
Hi!

**Comment by gabrielpoca** [comment]
Hi!
It seems to work for me. I've pushed an example [here](https://github.com/still-ex/still/commit/a2ca84c599b129edd47631b5f9ad2f74a912cba0) for you. The only thing I did differently is I changed the order of `EEx` with `FrontMatter` because otherwise, the variables defined in frontmatter will not be available when it runs through EEx. If you're not using variables from frontmatter, then what you did should work. Do you see any errors on the console?

**Comment by elinol** [comment]
Hi! 
After putting the html-preprocessor in default preprocessors instead of in config.exs is works out alright.
Thanks for helping me out!

**Comment by lawik** [comment]
Wait @gabrielpoca, you mean that we should be changing the preprocessors by editing the still dependency? This case is using Still as a dep in another application.

I imagine the config :still, preprocessors key should work and that's what we aren't having luck with.

**Comment by gabrielpoca** [comment]
@lawik no no, you should change it in the config like we show [here](https://hexdocs.pm/still/preprocessors.html#content). @elinol I'm sorry, I took the easiest route in my example, [here's a similar example in my website that uses Still]( https://github.com/gabrielpoca/gabrielpoca.com/commit/7f462220295163628fa10dd1eb9e77acd9232a93)

**Comment by lawik** [comment]
Alright, we are having some weird problems. Will keep digging. 

Thanks :)

**Comment by gabrielpoca** [comment]
@lawik 👍  let me know if I can help

**Comment by lawik** [comment]
Elin pinned it down. We hadn't aliased the modules in the config. This triggers not error from what I saw :D
It should probably check if there is a `run` function defined and log an error for a bad preprocessor or something, because this is a fairly hard-to-debug failure.

**Comment by frm** [comment]
> this is a fairly hard-to-debug failure.

Second this, saw a few other users with the same issue. The fact that we have aliased is confusing people. I'll update the docs and try to add a specific error

**Comment by gabrielpoca** [comment]
![image](https://user-images.githubusercontent.com/934580/117349023-d10a9a00-aea2-11eb-9cf2-3c965f8dc366.png)
Yeah, it already happened to me as well. I tried it out, and I get this error in the console, but we should push this to the error overlay.

**Comment by lawik** [comment]
For us it might have drowned, we had some .DS_Store errors so I might have
conflated them. Sounds like good fixes :)

**Comment by gabrielpoca** [comment]
Found it 😅 there's a bug in the error reporting system. Those are the worst 😭 this is what I see now that's fixed

![localhost_3000_](https://user-images.githubusercontent.com/934580/117364530-ec32d500-aeb5-11eb-834c-60c1fde366d6.png)

It could be a better error, but it's an improvement. I'll open a fix
