### ISSUE TITLE
Dynamic pages and datafiles

### ISSUE THREAD

**Issue by expilo** [still-ex/still#169]
I wonder if it might be possible to generate pages dynamically using datafiles with Still?

**Comment by gabrielpoca** [comment]
Hello! I had some ideas to implement [datafiles like 11ty](https://www.11ty.dev/docs/data-global/). But can you elaborate on what you're thinking?

**Comment by expilo** [comment]
For the starters  (and maybe it would be good enough) it could be something like the [dynamic pages](https://middlemanapp.com/advanced/dynamic-pages/) and [datafiles](https://middlemanapp.com/advanced/data-files/). I find them pretty useful when making more complex websites. Of course, there are probably other ways to do it. Basically any solution which would take a data structure and generate pages dynamically based on the records, queries or modified data coming from data files would do.

**Comment by gabrielpoca** [comment]
I like this. I can easily implement datafiles because it's just an abstraction. Dynamic pages are a bit harder because the framework is still coupled to 1 page = 1 file. I definitely want to change that because to support responsive images I had to "hack" it. Let me see what I can do. Btw, are you available for code reviews? Fernando doesn't have a lot of time right now and I could use an extra pair of eyes.

**Comment by expilo** [comment]
I can't promise fast feedback,  but I will definitely need a new static site generator so I will keep an eye. However dynamic pages are a must for me. It could be possible perhaps to generate source pages from a datafile before but then the point of implementing datafiles is missed. Unless one wants to present data from datafile in a single page, of course.

**Comment by frm** [comment]
I've been away for a while so pardon any mistake while I jog my memory but don't we have a synchronous step before the traversal ends? I'm wondering if we can do a version of passthrough copy to shortcircuit something like the middleman proxy.

**Comment by gabrielpoca** [comment]
We can, but I do like [eleventy's solution better](https://www.11ty.dev/docs/pages-from-data/). Can you have a look?

**Comment by gabrielpoca** [comment]
Closing because it's already [implemented](https://hexdocs.pm/still/pagination.html#content).
