### ISSUE TITLE
Dependencies don't compile on Windows

### ISSUE THREAD

**Issue by bmitc** [still-ex/still#185]
Reproduction steps, on Windows 11:

1. `mix archive.install hex still_new`
2. `mix still.new my_site`
3. `mix deps.get`
4. `mix still.dev`

Step (4) returns the error:

> ==> markdown
could not compile dependency :markdown, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile markdown", update it with "mix deps.update markdown" or clean it with "mix deps.clean markdown"
** (ErlangError) Erlang error: :enoent
    (elixir 1.13.3) lib/system.ex:1044: System.cmd("nmake", ["/F", "Makefile.win", "priv\\markdown.dll"], [stderr_to_stdout: true])
    c:/Users/\<username\>/Desktop/my_site/deps/markdown/mix.exs:5: Mix.Tasks.Compile.Hoedown.run/1
    (mix 1.13.3) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.13.3) lib/mix/tasks/compile.all.ex:92: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.13.3) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
    (mix 1.13.3) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2
    (mix 1.13.3) lib/mix/tasks/compile.all.ex:36: Mix.Tasks.Compile.All.run/1
    (mix 1.13.3) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3

This of course probably stems from the underlying dependencies, either Hoedown and/or Markdown, but it prevents this package being used on Windows. It's also possible the installation section in the README will need updating.

**Comment by gabrielpoca** [comment]
@bmitc I need to make a new release because I've already removed that dep from master. I'll look into it in a bit 👍

**Comment by bmitc** [comment]
Sounds great! I tried debugging which of the dependencies of Markdown was causing this, but if you've removed Markdown, then that probably removes the troubled dependency. Thanks for taking a look into it!

**Comment by gabrielpoca** [comment]
@bmitc can you upgrade to 0.8 ? I don't have Windows to test it, but I removed that dependency, so it should be one step closer

**Comment by bmitc** [comment]
Upgraded to `0.8` and none of `mix deps.get`, `mix compile`, `mix test`, or `mix still.dev` error out on dependencies now. Thanks for the fix!
