### ISSUE TITLE
Image Processing

### ISSUE THREAD

**Issue by gabrielpoca** [still-ex/still#57]
I think Still should solve the hardest parts of building a website out of the box. Dealing with images on the web isn't simple: you need multiple sizes, the right "srcset" attributes, lazy loading, etc. Gatsby is the only framework I've used that does it right and I think [we should draw some inspiration from it](https://www.gatsbyjs.com/plugins/gatsby-image/). Here's what we need to do:

* resize large images to the necessary sizes.
* generate smaller images to be used by devices with smaller screens or resolution.
* optimize images.
* lazy-loading.

In gatsby, they distinguish between `fluid` and `fixed` images. You use `fixed` images when you know the image's width and height and you only need to change images based on the screen resolution. I propose we start with two functions:

```
<div>
  <%= fluid_image "banner.png", max_width: "1000px", alt: "Something", class: "Image" %>
  <%= fixed_image "banner.png", width: "1000px", alt: "Something", id: "#banner" %>
</div>
```

We'll need to write a preprocessor, two view helpers, and maybe change the `SourceFile` module to allow for the attributes.

@naps62 gatsby uses https://github.com/libvips/libvips because:

> Resizing an image is typically 4x-5x faster than using the quickest ImageMagick and GraphicsMagick settings due to its use of libvips.

[Source](https://github.com/lovell/sharp). What do you think?

**Comment by naps62** [comment]
@gabrielpoca rust comes in and says: "hold my beer, vips"

https://github.com/imazen/imageflow

comparison between imageflow, vips and imagemagick:

**Comment by gabrielpoca** [comment]
Nice! I can't find any bindings, I guess it's time for rustler?

**Comment by naps62** [comment]
I guess, yes

**Comment by frm** [comment]
This can be closed, right? @gabrielpoca - we already have rudimentary image processing

**Comment by gabrielpoca** [comment]
Yap
